# Aufgabe 1

In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
def getKNearestNeighbors(x,X,k):  # realizes nearest neighbor search of x in database
    """
    compute the k nearest neighbors for a query vector x given a data matrix X
    :param x: the query vector x
    :param X: the N x D data matrix (in each row there is data vector) as a numpy array
    :param k: number of nearest-neighbors to be returned
    :return: return list of k line indixes referring to the k nearest neighbors of x in X
    """
    
    #verwenden von np.linalg.norm und np.argsort!
    
    
    d=[sum([((x[j] - X[i][j])**2) for j in range(len(X[0]))]) for i in range(len(X))]

    return [d.index(sorted(d)[i]) for i in range(k)]

In [3]:
# ***** MAIN PROGRAM ********

# (i) Generate dummy data 
X = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]]);      # data matrix X: list of data vectors (=database) of dimension D=3
x = np.array([1.5,3.6,5.7]);                          # a test data vector
print("Data matrix X=\n",X)
print("Test vector x=",x)

Data matrix X=
 [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
Test vector x= [1.5 3.6 5.7]


In [4]:
# (ii) Print all Euklidean distances to test vector x
print("Euklidean distances to x: ", [LA.norm(x-X[i]) for i in range(len(X))])   # REPLACE! compute list of Euklidean distances   

Euklidean distances to x:  [3.178049716414141, 1.8708286933869709, 1.7029386365926402, 2.8809720581775866]


In [5]:
# (iii) Search for k nearest neighbor
k=2
idx_knn = getKNearestNeighbors(x,X,k)                # get indexes of k nearest neighbors
print("idx_knn=",idx_knn)

idx_knn= [2, 1]


In [6]:
# (iv) output results
print("The k Nearest Neighbors of x are the following vectors:")
for i in range(k):
    idx=idx_knn[i]
    print("The", i+1, "th nearest neighbor is: X[",idx,"]=",X[idx]," with distance ", np.linalg.norm(X[idx]-x))

The k Nearest Neighbors of x are the following vectors:
The 1 th nearest neighbor is: X[ 2 ]= [3 4 5]  with distance  1.7029386365926402
The 2 th nearest neighbor is: X[ 1 ]= [2 3 4]  with distance  1.8708286933869709
