# Aufgabe 1.4

In [1]:
import numpy as np
import pandas as pd
from time import perf_counter
from random import randint
from V1A2_Classifier import *

In [2]:
# (I) Load data 
forestdata  = pd.read_csv('../DATA/ForestTypes/ForestTypesData.csv'); # load data as pandas data frame 
classlabels = ['s','h','d','o'];                                      # possible class labels (C=4) 
classidx    = {classlabels[i]:i for i in range(len(classlabels))}     # dict for mapping classlabel to index 
C           = len(classlabels)        # number of classes (Note: K is now the number of nearest-neighbors!!!!!!)
T_txt = forestdata.values[:,0]        # array of class labels of data vectors (class label is first data attribute)
X = forestdata.values[:,1:]           # array of feature vectors (features are remaining attributes)
T = [classidx[t.strip()] for t in T_txt]          # transform text labels 's','h','d','o' to numeric lables 0,1,2,3
N,D=X.shape                           # size and dimensionality of data set
print("Data set 'ForestData' has size N=", N, " and dimensionality D=",D, " and C=", C, " different classes")
print("X[0..9]=\n",X[0:10])
print("T_txt[0..9]=\n",T_txt[0:10])
print("T[0..9]=\n",T[0:10])


Data set 'ForestData' has size N= 523  and dimensionality D= 27  and C= 4  different classes
X[0..9]=
 [[39 36 57 91 59 101 93 27 60 75.7 14.86 40.35 7.97 -32.92 -38.92 -14.94
  4.47 -2.36 -18.41 -1.88 -6.43 -21.03 -1.6 -6.18 -22.5 -5.2 -7.86]
 [84 30 57 112 51 98 92 26 62 30.58 20.42 39.83 -16.74 -24.92 -36.33
  -15.67 8.16 -2.26 -16.27 -1.95 -6.25 -18.79 -1.99 -6.18 -23.41 -8.87
  -10.83]
 [53 25 49 99 51 93 84 26 58 63.2 26.7 49.28 3.25 -24.89 -30.38 -3.6 4.15
  -1.46 -15.92 -1.79 -4.64 -17.73 -0.48 -4.69 -19.97 -4.1 -7.07]
 [59 26 49 103 47 92 82 25 56 55.54 24.5 47.9 -6.2 -20.98 -30.28 -5.03
  7.77 2.68 -13.77 -2.53 -6.34 -22.03 -2.34 -6.6 -27.1 -7.99 -10.81]
 [57 49 66 103 64 106 114 28 59 59.44 2.62 32.02 -1.33 -37.99 -43.57
  -34.25 1.83 -2.94 -21.74 -1.64 -4.62 -23.74 -0.85 -5.5 -22.83 -2.74
  -5.84]
 [85 28 56 120 52 98 101 27 65 35.14 23.43 42.29 -16.58 -25.43 -34.14
  -17.45 1.58 -10.28 -26.18 -1.89 -5.89 -34.92 -1.89 -8.05 -29.72 -1.94
  -4.94]
 [56 29 50 93 51 94 77 26 58

# a) und b)

In [3]:
# (II) Test KNN-classifier with S-fold cross validation
S_list=[5]                         # parameter S for cross validation; INSERT appropriate values
K_list=[3]                            # number K of nearest neighbors; INSERT appropriate values
accuracy = np.zeros((len(S_list),len(K_list)));   # array to save accuracy of classifier for each value of S and K
for i in range(len(S_list)):
    S=S_list[i]                      # do an S-fold cross validation
    for j in range(len(K_list)):
        K=K_list[j]
        t1=perf_counter()                   # start time
        knnc = FastKNNClassifier(C,K)                            # REPLACE! create appropriate KNN classifier (with kd-trees) 
        pE,pCE = knnc.crossvalidate(S,X,T)                          # REPLACE! Do S-fold cross validation and get error probabilities / confusion matrix
        t2=perf_counter()                            # end time
        time_comp=t2-t1                       # computing time in seconds
        print("\nS=",S," fold cross validation using the",K,"-NNClassifier with KD-Trees yields the following results:")
        print("Classification error probability = ", pE)
        print("Accuracy = ", 1.0-pE)
        print("Confusion Error Probabilities p(class i|class j) = \n", pCE)
        print("Computing time = ", time_comp, " sec")
        accuracy[i,j]=1.0-pE
print("\naccuracy=\n",accuracy)
print("\np_classerror=\n",1.0-accuracy)


S= 5  fold cross validation using the 3 -NNClassifier with KD-Trees yields the following results:
Classification error probability =  0.45124282982791586
Accuracy =  0.5487571701720841
Confusion Error Probabilities p(class i|class j) = 
 [[0.18974359 0.02325581 0.12578616 0.03614458]
 [0.21538462 0.89534884 0.06289308 0.19277108]
 [0.24102564 0.02325581 0.75471698 0.13253012]
 [0.35384615 0.05813953 0.05660377 0.63855422]]
Computing time =  2.2980376  sec

accuracy=
 [[0.54875717]]

p_classerror=
 [[0.45124283]]


# c)

In [4]:
S_list=[1,2,3,5,10,100]                         # parameter S for cross validation; INSERT appropriate values
K_list=[2,3,5,15,100]                          # number K of nearest neighbors; INSERT appropriate values
accuracy = np.zeros((len(S_list),len(K_list)));   # array to save accuracy of classifier for each value of S and K
for i in range(len(S_list)):
    S=S_list[i]                      # do an S-fold cross validation
    for j in range(len(K_list)):
        K=K_list[j]
        t1=perf_counter()                   # start time
        knnc = FastKNNClassifier(C,K)                            # REPLACE! create appropriate KNN classifier (with kd-trees) 
        pE,pCE = knnc.crossvalidate(S,X,T)                          # REPLACE! Do S-fold cross validation and get error probabilities / confusion matrix
        t2=perf_counter()                            # end time
        time_comp=t2-t1                       # computing time in seconds
        print("\nS=",S," fold cross validation using the",K,"-NNClassifier with KD-Trees yields the following results:")
        print("Classification error probability = ", pE)
        print("Accuracy = ", 1.0-pE)
        print("Confusion Error Probabilities p(class i|class j) = \n", pCE)
        print("Computing time = ", time_comp, " sec")
        accuracy[i,j]=1.0-pE
print("\naccuracy=\n",accuracy)
print("\np_classerror=\n",1.0-accuracy)


S= 1  fold cross validation using the 2 -NNClassifier with KD-Trees yields the following results:
Classification error probability =  0.5525812619502868
Accuracy =  0.4474187380497132
Confusion Error Probabilities p(class i|class j) = 
 [[0.         0.01162791 0.         0.        ]
 [0.         0.88372093 0.00628931 0.80722892]
 [1.         0.10465116 0.99371069 0.19277108]
 [0.         0.         0.         0.        ]]
Computing time =  2.126216  sec

S= 1  fold cross validation using the 3 -NNClassifier with KD-Trees yields the following results:
Classification error probability =  0.8432122370936902
Accuracy =  0.1567877629063098
Confusion Error Probabilities p(class i|class j) = 
 [[0.02564103 0.70930233 0.62264151 0.12048193]
 [0.96923077 0.06976744 0.03144654 0.02409639]
 [0.         0.         0.         0.        ]
 [0.00512821 0.22093023 0.34591195 0.85542169]]
Computing time =  2.3579205000000005  sec

S= 1  fold cross validation using the 5 -NNClassifier with KD-Trees yie


S= 5  fold cross validation using the 15 -NNClassifier with KD-Trees yields the following results:
Classification error probability =  0.8910133843212237
Accuracy =  0.10898661567877632
Confusion Error Probabilities p(class i|class j) = 
 [[0.04615385 0.69767442 0.69811321 0.24096386]
 [0.         0.         0.         0.        ]
 [0.95384615 0.30232558 0.30188679 0.75903614]
 [0.         0.         0.         0.        ]]
Computing time =  3.132790700000001  sec

S= 5  fold cross validation using the 100 -NNClassifier with KD-Trees yields the following results:
Classification error probability =  0.722753346080306
Accuracy =  0.27724665391969405
Confusion Error Probabilities p(class i|class j) = 
 [[0.03076923 0.18604651 0.14465409 0.34939759]
 [0.         0.         0.         0.        ]
 [0.96923077 0.81395349 0.85534591 0.61445783]
 [0.         0.         0.         0.03614458]]
Computing time =  4.710222099999996  sec

S= 10  fold cross validation using the 2 -NNClassifier with